### ISSUE TITLE
Cannot work with plug-in:Remaining time

### ISSUE THREAD

**Issue by PrentissLiu** [TRIAEIOU/Flexible-cloze#1]
Hi developers, try to use the plug-in you developed on Anki, feel very good work!
But I found that plug-ins and mods don't work together(Remaining time,https://ankiweb.net/shared/info/1508357010). Specific performance in the preview interface can normally display the front and back of the card. 　But after the plug-in Remaining time is installed, the entire page is white and you can't see anything.

![image](https://user-images.githubusercontent.com/32979510/154475638-f9a9956a-f617-4b6a-93b8-3d99503928d8.png)

**Comment by triaeiou** [comment]
Thanks for the bug report. A quick look shows that the Remaining Time addon HTML doesn't mix well with the FCZ HTML. The FCZ content is still there (and most likely works as it should), however Remaining Time inserts an HTML &lt;div&gt; tag with a white background color that fills the entire screen on top of FCZ. For some reason the Remaining Time tag isn't inserted into the document flow together with the FCZ HTML, I am not sure that the issue is with FCZ, you may want to alert trganki to have a look at it as well.

**Comment by triaeiou** [comment]
Ok, reimplemented the HTML on the front side and it now seems to work with https://ankiweb.net/shared/info/1508357010 - feel free to check out the latest FCZ version.
